### ISSUE TITLE
Bandit has an upstream security vulnerability with Gitpython

### ISSUE THREAD

**Issue by epicserve** [epicserve/django-base-site#443]
The vulnerability with Gitpython has been reported Bandit issue [#1050](https://github.com/PyCQA/bandit/issues/1050). As soon as Bandit has made a release with a fix this issue can resolved by upgrading Bandit.

**Comment by habbdt** [comment]
Could you please provide an estimate on when the new version of Bandit with this fix will become available? Thank you.

**Comment by epicserve** [comment]
This has been resolved.
