### ISSUE TITLE
Select latest stable Python version

### ISSUE THREAD

**Issue by codyfletcher** [epicserve/django-base-site#456]
I would create a PR, but figured the end result would depend on your preference.

Locally, in my Dockerfile.web I changed `python:3-buster` to `python:3.11-bookworm` (in 2 places)

Reasoning:
1. Latest "stable" release of debian is [bookworm](https://www.debian.org/releases/) (buster is "oldoldstable")
2. Selected Python version `3.11` instead of `3` to get the latest stable minor version. That seemed like a good idea. :)

**Comment by epicserve** [comment]
@codyfletcher, your reasoning seems sound to me. If you want to create a PR, go for it!

**Comment by epicserve** [comment]
I'm fine with using `titank12.com](python:3.11-bookworm`.

**Comment by epicserve** [comment]
This has been merged in.
