### ISSUE TITLE
 Normalize HTML templates to 2 spaces

### ISSUE THREAD

**Issue by epicserve** [epicserve/django-base-site#53]

**Comment by supsa-ak** [comment]
Hi, I am willing to work on this issue. Please give me some brief about it. Thanks

**Comment by epicserve** [comment]
@supsa-ak, thank you, that is appreciated, but I think we can close this issue because of the following issue I'm almost done with.

https://github.com/epicserve/django-base-site/issues/50

**Comment by epicserve** [comment]
@supsa-ak, I apologize, I thought this was another issue. I'll re-open this issue.

If you want to do this issue that would be great!

I was thinking of either using a regular expression to do a search and replace to replace for spaces with two in all html templates or I was going to try an auto formatter for Django html templates.

**Comment by epicserve** [comment]
@supsa-ak, FYI, it might be best to wait until, https://github.com/epicserve/django-base-site/issues/50, is merged in because I've touched almost every template and there would be a lot of conflict.

**Comment by epicserve** [comment]
@supsa-ak, I was on a roll today, so I got this one done.
