### ISSUE TITLE
/main/? in bash <(curl -s https://raw.githubusercontent.com/epicserve/django-base-site/main/scripts/start_new_project)

### ISSUE THREAD

**Issue by hanshendrickx** [epicserve/django-base-site#668]
I cloned the git; Running the bash:
C:\Users\*****\docker\django-base-site>cd main
The system cannot find the path specified.

Maybe the project's tree has changed?

**Comment by epicserve** [comment]
Hi @hanshendrickx ,

I'm not supporting Windows at this time since I don't have a Windows machine for testing. You could try the manual method of getting it up and running, but keep in mind this project is mainly designed to run under Docker and Docker Compose for development.

See also #667
